### ISSUE TITLE
Looking forward to the complete pipeline

### ISSUE THREAD

**Issue by yangfeng-Lyu** [Forrest-110/FastMAC#1]
Hi！
You  have done a fantastic job and I look forward to realizing the complete pipeline for learning!

**Comment by Forrest-110** [comment]
Thanks. We'd love to release it soon but I'm quite busy this summer. The complete SLAM pipeline is estimated to be released in September.

**Comment by xl232lx** [comment]
Hi author, your research is excellent and I look forward to completing the integration project soon！！！

**Comment by Forrest-110** [comment]
Thank you for your support! A simple integration example has been provided.
