### ISSUE TITLE
How to use FastMAC

### ISSUE THREAD

**Issue by xl232lx** [Forrest-110/FastMAC#2]
Hi
I use FastMAC to get three txt files, how to combine into MAC？

**Comment by Forrest-110** [comment]
Please begin by installing [MAC](https://github.com/zhangxy0517/3D-Registration-with-Maximal-Cliques/tree/main) following the provided instructions.

For a quick test, we recommend using the [KITTI dataset](https://pan.baidu.com/s/1KZS2LccseYJZWMmDG0xDbw) provided by MAC. Simply run our downsampling code on the correspondence file, replace it with the downsampled version, and then execute MAC.

For your custom dataset, an easy approach is to organize it into a directory containing three files: correspondence, gtlabel, and gtmatrix. The ground truth file serves merely as a placeholder to minimize modifications to the MAC code. Treat your custom dataset the same as the KITTI dataset within MAC by adjusting the number of point cloud samples and other hyperparameters.

If you can wait a bit longer, we plan to release a comprehensive Python version pipeline integrated with MAC soon. Please do not hesitate to contact us if you encounter any issues!

**Comment by xl232lx** [comment]
Thank you for your reply, your work is very good, looking forward to your optimized version！！！

**Comment by xl232lx** [comment]
Hello, can I ask you how to make these three txt(fcgf@corr.txt, fcgf@gtlabel.txt, fcgf@gtmat.txt) files through my two PCD files?

**Comment by Forrest-110** [comment]
For a given point cloud [N, 3], use a descriptor (e.g. [FPFH](https://pcl.readthedocs.io/projects/tutorials/en/latest/fpfh_estimation.html) or [FCGF](https://github.com/chrischoy/FCGF)) to get a pointwise feature [N, D]. Then for any two point clouds they can form a similarity matrix [N, M] and the similarity score can be defined as the distance between features. With the similarity matrix, one can form the correspondence [N, 1] simply by finding the nearest neighbor. For more details, please see the Appendix A.3 of our [paper](https://arxiv.org/pdf/2403.08770) or the [code of MAC](https://github.com/zhangxy0517/3D-Registration-with-Maximal-Cliques/blob/f03f1a24ed74128433e40970fed6e01d6a09d780/Python_implement/example_with_fpfh_fcgf.py#L199).

gtlabel is used to test whether your correspondence is right. It is not important so you can just randomly generate a [N, 1] matrix.

gtmatrix can be found using ICP as a pseudo ground truth. Or if your point cloud is generated using a known transformation, you already have it!

**Comment by xl232lx** [comment]
Ok, thanks. I'll do some research.

**Comment by songhc8** [comment]
> Please begin by installing [MAC](https://github.com/zhangxy0517/3D-Registration-with-Maximal-Cliques/tree/main) following the provided instructions.
> 
> For a quick test, we recommend using the [KITTI dataset](https://pan.baidu.com/s/1KZS2LccseYJZWMmDG0xDbw) provided by MAC. Simply run our downsampling code on the correspondence file, replace it with the downsampled version, and then execute MAC.
> 
> For your custom dataset, an easy approach is to organize it into a directory containing three files: correspondence, gtlabel, and gtmatrix. The ground truth file serves merely as a placeholder to minimize modifications to the MAC code. Treat your custom dataset the same as the KITTI dataset within MAC by adjusting the number of point cloud samples and other hyperparameters.
> 
> If you can wait a bit longer, we plan to release a comprehensive Python version pipeline integrated with MAC soon. Please do not hesitate to contact us if you encounter any issues!

Hi, Do you mean the output of FastMAC is the input of MAC algorithm?

**Comment by Forrest-110** [comment]
> > Please begin by installing [MAC](https://github.com/zhangxy0517/3D-Registration-with-Maximal-Cliques/tree/main) following the provided instructions.
> > For a quick test, we recommend using the [KITTI dataset](https://pan.baidu.com/s/1KZS2LccseYJZWMmDG0xDbw) provided by MAC. Simply run our downsampling code on the correspondence file, replace it with the downsampled version, and then execute MAC.
> > For your custom dataset, an easy approach is to organize it into a directory containing three files: correspondence, gtlabel, and gtmatrix. The ground truth file serves merely as a placeholder to minimize modifications to the MAC code. Treat your custom dataset the same as the KITTI dataset within MAC by adjusting the number of point cloud samples and other hyperparameters.
> > If you can wait a bit longer, we plan to release a comprehensive Python version pipeline integrated with MAC soon. Please do not hesitate to contact us if you encounter any issues!
> 
> Hi, Do you mean the output of FastMAC is the input of MAC algorithm?

Yes!

**Comment by yyxmoon123** [comment]
请问有训练代码吗

**Comment by xl232lx** [comment]
Hello author, I see that you have updated the project here, now I want to directly register my own two-frame pcd point cloud file what are the steps, thank you

**Comment by Forrest-110** [comment]
Please follow the steps:
1. First you may need a correspondence extractor like [GeoTransformer](https://github.com/qinzheng93/GeoTransformer/). It should take your two-frame point cloud as input and output correspondences, working like the function https://github.com/Forrest-110/FastMAC/blob/b6aa26f07abf08a30f8be387657bdcebf63cb37d/pipeline_SLAM/utils/extract_corr.py#L493

2. With the correspondences, you can easily use the code below to get the final transformation:
https://github.com/Forrest-110/FastMAC/blob/b6aa26f07abf08a30f8be387657bdcebf63cb37d/pipeline_SLAM/pipeline.py#L95-L96

**Comment by xl232lx** [comment]
Ok, thank you very much!

**Comment by yyxmoon123** [comment]
> 请按照以下步骤操作：
> 
> 1. 首先，你可能需要一个像[GeoTransformer](https://github.com/qinzheng93/GeoTransformer/)这样的对应提取器。它应该将你的两帧点云作为输入和输出对应，工作方式类似于函数https://github.com/Forrest-110/FastMAC/blob/b6aa26f07abf08a30f8be387657bdcebf63cb37d/pipeline_SLAM/utils/extract_corr.py#L493
> 2. 通过对应关系，您可以轻松使用以下代码来获得最终的转换：
>    https://github.com/Forrest-110/FastMAC/blob/b6aa26f07abf08a30f8be387657bdcebf63cb37d/pipeline_SLAM/pipeline.py#L95-L96

作者您好，我看了一下registration()中的代码，发现与MAC很相似，请问一下FastMAC对MAC的加速机制在代码中怎么体现呢，感谢您的答疑

**Comment by Forrest-110** [comment]
MAC is slow in maximal clique search due to its large correspondence graph. Through previous correspondence downsampling, we decrease the size of the correspondence graph while maintaining its performance.

**Comment by yyxmoon123** [comment]
> 由于 MAC 的对应图很大，因此在最大团搜索中速度较慢。通过先前的对应下采样，我们减小了对应图的大小，同时保持了其性能。

感谢您的回复，我的理解是通过downsample()实现随机谱采样，后续直接使用接入Mac进行变换矩阵的计算，请问我的理解是对的吗？感谢您的解答！

**Comment by Forrest-110** [comment]
> > 由于 MAC 的对应图很大，因此在最大团搜索中速度较慢。通过先前的对应下采样，我们减小了对应图的大小，同时保持了其性能。
> 
> 感谢您的回复，我的理解是通过downsample()实现随机谱采样，后续直接使用接入Mac进行变换矩阵的计算，请问我的理解是对的吗？感谢您的解答！

yes! we didn't directly modify MAC

**Comment by jujimeizuo** [comment]
> Hello author, I see that you have updated the project here, now I want to directly register my own two-frame pcd point cloud file what are the steps, thank you

Hello bro, do you have a pipeline .py for custom .ply files?  I wanna directly register my own two-frame .ply files too. Did you write an input by yourself?
