### ISSUE TITLE
How to train FastMAC

### ISSUE THREAD

**Issue by yyxmoon123** [Forrest-110/FastMAC#3]
您好 请问一下您有公开训练代码的计划吗

**Comment by Forrest-110** [comment]
您好，我们的工作不包括训练环节，无需训练。

**Comment by yyxmoon123** [comment]
感谢，请问一下，您公布的代码是需要通过对应关系计算刚性旋转矩阵吗

**Comment by Forrest-110** [comment]
是的，通过少量置信度高的对应关系计算

**Comment by yyxmoon123** [comment]
好的十分感谢您的工作，FastMAC可以作为MAC的一个前置插件吗？比如我用FastMAC得出三个txt结果，然后使用这个结果作为MAC的输入，MAC输出最后的配准结果，请问我可以这样理解吗？

**Comment by Forrest-110** [comment]
可以的，可以参照 https://github.com/Forrest-110/FastMAC/blob/b6aa26f07abf08a30f8be387657bdcebf63cb37d/pipeline_SLAM/pipeline.py#L93-L96

**Comment by yyxmoon123** [comment]
十分感谢！
